---
# - vars:
#     ansible_become_pass: "{{ lookup('env', 'CVTS_BECOME_PASSWORD') }}"
- import_playbook: mapmatcher.yaml
# - import_playbook: B-fail2ban-ssh.yml
# - import_playbook: C-enable-watchdog.yml
